config/routes.rb
Rails.application.routes.draw do
  get 'tarif', to: 'tarif#index'
  
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tarif_controller.rb
class TarifController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
require "erb"

module ApplicationHelper

  def active_path?(path)
    request.path == path ? 'active' : ''
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tarif_helper.rb
module TarifHelper
end

app/views/home/index.html.erb
<div id="home" class="container transparent">
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="contact col">
    <h2>Contact</h2>
    <hr/>

    <div class="content">
      <a href="mailto:contact@exemple.fr"><i class="i-mail"></i>contact@exemple.fr</a>
      <a href="tel:+330000000000"><i class="i-phone"></i>+33 (0)0 00 00 00 00</a>
      <div class="socials">
        <a href="#"><i class="i-facebook"></i></a>
        <a href="#"><i class="i-instagram"></i></a>
        <a href="#"><i class="i-vimeo"></i></a>
      </div>
    </div>
  </div>

  <div class="adress col">
    <h2>Address</h2>
    <hr/>

    <div class="content">
      <div class="background"></div>
      <p>
        1 Avenue d'Aquitaine<br/>
        La Nouvelle-Aquitaine,<br/>
        33000 France
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>Animals</h1>

  <nav>
    <%= link_to "accueil", root_path, :class => active_path?(root_path) %>
    <%= link_to "horaires & tarifs", tarif_path, :class => active_path?(tarif_path) %>
    <a href="<%= root_path %>">Les animaux</a>
    <a href="<%= root_path %>">les news</a>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="background"></div>

    <%= render('layouts/header') %>

    <%= yield %>

    <%= render('layouts/footer') %>
  </body>
</html>

app/views/tarif/index.html.erb
<div id="tarif" class="container">

  <h2>Horaires et Tarifs</h2>
  <hr/>
  <br/>

  <h3>Horaires</h3>
  <p>Hiver - Printemps <> Été - Automne</p>
  <p>10h-18h <> 9h-19h</p>

  <br/>

  <h3>Tarifs</h3>
  <section class="tarifs">
    <div class="card">
      <div class="pic">
        <i class="i-child"></i>
      </div>

      <h3>Enfant*</h3>

      <span class="price">12€</span>

      <div class="more-info">*3 à 12ans</div>
    </div>

    <div class="card">
      <div class="pic">
        <i class="i-person"></i>
      </div>

      <h3>Adulte</h3>

      <span class="price">18€</span>
    </div>

    <div class="card">
      <div class="pic">
        <i class="i-group"></i>
      </div>

      <h3>Groupe*</h3>

      <div class="description">
        <p><span class="price">15€</span>Adulte(s)</p>
        <p><span class="price">9€</span>Enfant(s)</p>
      </div>

      <div class="more-info">*Minimum 15 personnes</div>
    </div>
  </section>

  <br/>
  <p>Mode de paiement CB, especes, Cheque ANCV</p>
  <p>Autre infos: parkings gratuits</p>

  <br/>

  <h3>Informations générales</h3>
  <p>Chiens non admis, nourrissage animaux, restauration rapide et boutique, accès handicapés</p>

</div>